default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-yaml
    -   id: pretty-format-json
        args: ["--autofix"]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
        -   id: autopep8

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: ["--exclude", "venv/,.tox/,.eggs/"]

-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        args: ["--sl"]

-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args: ["--strict"]
        additional_dependencies:
          - pydantic

-   repo: local
    hooks:
    -   id: python-bandit-vulnerability-check
        name: bandit
        entry: bandit
        args: ['--ini', 'setup.cfg', '-x', 'repokid/tests/', '-r', 'repokid']
        language: system
        pass_filenames: false
