language: python

matrix:
  include:
    - python: "3.7"

# horrible thing to fix cloudaux/boto/google issue
before_install:
  - sudo rm -f /etc/boto.cfg

install:
  - pip install coveralls
  - pip install bandit
  - pip install .
  - pip install -r test-requirements.txt

script:
  - coverage run --source repokid -m py.test
  - bandit -r . -ll -ii -x repokid/tests/
  - flake8 .

after_success:
  - coveralls

notifications:
  email:
    - tmcpeak@netflix.com
    - ccastrapel@netflix.com

